parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Project\SubProject\:
        resource: '../src/'
        exclude:
            - '../src/Common/Infrastructure/Symfony/Kernel.php'

    Project\SubProject\Common\Interfaces\Controller\:
        resource: '../src/Common/Interfaces/Controller/'
        tags: ['controller.service_arguments']

